config/routes.rb
Bucketlist::Application.routes.draw do
  resources :comments, :only => [:create]

  resources :destinations, :only => [:create, :destroy, :index]

 resources :todo_items do
 	member do
 		post :like
 	end

   collection do
  	post :update_position
  end
end
   root :to => 'todo_items#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :todo_item_id
  belongs_to :todo_item
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  attr_accessible :name
  has_many :todo_items


end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :todo_item_id, :user_id
  belongs_to :user
  belongs_to :todo_items
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base

  attr_accessible :completed, :name, :location, :latitude, :longitude, :destination_id

  validates :location, :presence => :true

  geocoded_by :geocoding_method
  after_validation :geocode

  has_many :comments, :dependent => :destroy
  belongs_to :destination
  belongs_to :user
  has_many :likes
  has_many :users, :through => :likes

  def geocoding_method
  	"#{self.location} #{destination.name}"

  end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :my_todo_items, :class_name => 'TodoItem'

  has_many :likes
  has_many :liked_items, :through => :likes, :class_name => 'TodoItem'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :load_default_user


  def load_default_user

  	session[:user_id] = User.first.id

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


 # before_filter  ,:only => [:show, :create, :update, :delete]

 def index
 	@comments = Comments.all 
 end


def create
	@comment = Comment.new(params[:comment])
	@comment.save!
	

	respond_to do |format|
		format.html do 
			render :partial => 'comments/comment', :locals => { :comment => @comment }, 
			:content_type => 'text/html'#<== same thing as render @comment 
		end
	
	end
	#render :template => 'comments/create', :locals => { :comment => @comment }, 
	#:content_type => 'text/javascript'
end
# def destroy
#     @comment = Comment.find(params[:id])
#     @comment.destroy

# end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController


	def index

		@destination = Destination.find(params[:id])

lat = params[:latitude] || 0
    long = params[:longitude] || 0

    @destination.near(params[:latitude], params[:longitude])
	end

	def create
		@destination = Destination.new(params[:destination])
		@destination.save!
		render @destination
	end

		def destroy

   	 	@destination = Destination.find(params[:id])
   	 	@destination.todo_items.each do |d|
   	 		d.destroy
   	 		d.comments.each do |c|
   	 			c.destroy
   	 		end
   	 	end

    	@destination.destroy
     	respond_to do |format|
     	 format.html { redirect_to todo_items_url }

    	end
    end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

	def index
		# @items = TodoItem.all
		order = params[:order] || :created_at
		@destinations = Destination.all
		@items = TodoItem.order(order).all
		respond_to do |format|
			format.html
			format.js{
				render :template => 'todo_items/order', :locals => {:todo_items => @items}
			}
		end
	end

	def like
		todo_item = TodoItem.find(params[:id])

		Like.create(:todo_item_id => todo_item.id, :user_id => User.first.id)
		render :nothing => true

	end


	def create

		@item = TodoItem.new(params[:todo_item])
		@item.save!
		render @item
	end

	def destroy

   	 	@item = TodoItem.find(params[:id])
    	@item.destroy
     	respond_to do |format|
     	 format.html { redirect_to todo_items_url }

    	end
    end


      def update_position
    params[:results].each do |i,results|
      TodoItem.update_all("position = #{results[1]}", "id = #{results[0]}")

  	end
      render :text => "Nice one"
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/comments/_comment.html.erb
<div class = "comment" data-item-id = "<%= comment.todo_item.id %>">
	<%= comment.body %>

	<div class = "info">
			<%= distance_of_time_in_words(comment.created_at) %>
					</div>
</div>

app/views/comments/_form.html.erb
<div class = "toggle">
	<h3>New Comment</h3>
</div>
<div class = "new-comment">


<%= form_for(Comment.new(:todo_item_id => item.id), :remote => true) do |f| %>


<%=  f.hidden_field :todo_item_id %>

<div class = "field">
		<%= f.text_area :body %>

</div>
<div class = "field">
		<%= f.submit  %>

</div>

<% end %>


</div>

app/views/destinations/_destination.html.erb
<div class = "destination_div">
	<div class = "destination_name">
		<h2><%= destination.name %></h2>
		<%= link_to "Remove?", destination, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

		<div id ="main">
	<p><%= link_to 'Sort By Name', todo_items_path(:order => :name), :remote => true, :locals => { :destination_id => destination.id} %></p>

		<p><%= link_to 'Sort Descending', todo_items_path(:order => :'name desc'), :remote => true, :locals => { :destination_id => destination.id} %></p>




<div class ="destination-<%= destination.id %>">

 <ol>


		<div class = "sortable">
		<% destination.todo_items.each do |d| %>

			<li>

			<%= render d %>
			</li>


		<% end %>
	</div>
<ol>

	</div>
	<%= render :partial => 'todo_items/form', :locals => { :destination_id => destination.id } %>

	</div>
</div>

app/views/destinations/_form.html.erb
<div class = "destination_form">

		<h3>New Destination</h3>
<%= form_for(Destination.new, :remote => true) do |f| %>





<div class = "field">

		<%= f.text_field :name %>

</div>


<br/>
<div class = "field">
		<%= f.submit  %>

</div>
<br/>

<% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bucketlist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.2.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="http://cdn.oesmith.co.uk/morris-0.4.2.min.js"></script>



<script type = "text/javascript" src= "https://maps.googleapis.com/maps/api/js?key=AIzaSyC74gnSe7p17ulcZUzgPJHxYurGg2bjRYg&sensor=false">
</script>




<script>
items = <%= raw(TodoItem.all.to_json) %>;

  $(document).ready(function() {
    initialize();
      <% TodoItem.all.each do |item| %>
         addMarker(<%=item.latitude%>, <%=item.longitude%>, '<%=item.name%>');

         <% end %>


      });




</script>


<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<div class = "todo_form">

		<h3>New To Do</h3>
<%= form_for(TodoItem.new(:destination_id => destination_id), :remote => true) do |f| %>



		<%= f.hidden_field :destination_id %>




<div class = "field">
<p>Name</p>
		<%= f.text_field :name %>

</div>

<div class = "field">
	<p>Location</p>
		<%= f.text_field :location %>

</div>
<br/>
<div class = "field">
		<%= f.submit  %>

</div>
<br/>

<% end %>


</div>

app/views/todo_items/_todo_item.html.erb
<div class = "todo_items"" <% todo_item.completed? ? 'completed' : '' %>" data-item-id = "<%= todo_item.destination_id %> "value = "<%= todo_item.position %>" data-ar-id = "<%= todo_item.id %>"/>

	<h3 class = "name"><%= todo_item.name %></h3>
	<div>
			 <p><%= link_to "Delete: #{todo_item.name}", todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></p>

			<p style = "color:white;"><%= link_to image_tag("thumbs_up.jpg"), like_todo_item_path(todo_item.id), :remote => true, method: :post %>

		 <%= "#{todo_item.likes.count} Likes" %></p>
				<% if todo_item.likes.first != nil  %>

					<% todo_item.users.uniq.each do |l| %>

					 <p style = "color:white;"><%= "Liked By #{l.name}" %> </p>

					<% end %>
			<% end %>

		 	<h3 style  ="color: white;">  <%= "#{todo_item.comments.count} Comments" %> </h3>
		 			<div class="comments-<%= todo_item.id %>">

				<% todo_item.comments.each do |comment| %>

					<%= render comment %>

				<% end %>


					</div>



	<%= render :partial => 'comments/form', :locals => { :item => todo_item } %>

	</div>
</div>

app/views/todo_items/index.html.erb
<div id = "nav">

       <%= render :partial => 'destinations/form' %>


</div>
<div id = "chart" style = "height:500; width: 500px; z-index:1; position: relative;  float: right;" >

</div>

<div class = "all">
    <% @destinations.each do |d| %>

       <%= render d %>

    <% end %>
</div>


<div id = "map-canvas"/>
</div>


<div class = "search-area">
<input type="search" id = "search-box" placeholder = "Search Term..." />
<div class = "apple">
</div>
</div>

<script>
createTable();


$("#chart").click(function () {
   $(this).fadeOut();
   console.log("Hello")
;});

</script>

app/views/todo_items/order.js.erb
<% todo_items.each do |i| %>
$(".destination-<%= i.destination.id %>").html("");
<% end %>


<% todo_items.each do |i| %>
	$('.destination-<%= i.destination.id %>').append('<%= escape_javascript(render i) %>')

<% end %>